name: CI API Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  repository_dispatch:
    types: [contentful.deploy]
jobs:
  slack-job:
    runs-on: ubuntu-latest
    steps:
      - name: Send slack message
        run: |
          echo "hello world"