name: CI API Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  repository_dispatch:
    types: [contentful.deploy]
  workflow_dispatch:  # Add this line
jobs:
  log-job:
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: |
          echo "hello world"
